name: Elixir test 

on: 
  push:
    branches:
      - main
    tags-ignore:
      - '**'
      
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-20.04]
        elixir_otp:
          # - { elixir: 1.13, otp: 22 }
          # - { elixir: 1.14, otp: 23 }
          # - { elixir: 1.15, otp: 24 }
          # - { elixir: 1.16, otp: 25 }
          - { elixir: 1.17, otp: 26 }
          - { elixir: 1.18, otp: 27 }

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: ${{ matrix.elixir_otp.elixir }}
          otp-version: ${{ matrix.elixir_otp.otp }}

      - name: Install dependencies
        run: mix deps.get

      - name: Run tests
        run: mix test


