name: Elixir test 

on:
  - push

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          # - otp: "25.0"
          #   elixir: "1.17"

          - os: ubuntu-latest
            otp: "24.0"
            elixir: "1.16"

          - os: ubuntu-latest
            otp: "24.0"
            elixir: "1.15"

          - os: ubuntu-latest
            otp: "23.0"
            elixir: "1.14"

          - os: ubuntu-latest
            otp: "22.0"
            elixir: "1.13"

          - os: windows-latest
            otp: "24.0"
            elixir: "1.16"

          - os: windows-latest
            otp: "24.0"
            elixir: "1.15"

          - os: windows-latest
            otp: "23.0"
            elixir: "1.14"

          - os: windows-latest
            otp: "22.0"
            elixir: "1.13"

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: ${{ matrix.elixir }}
          otp-version: ${{ matrix.otp }}

      - name: Install dependencies
        run: mix deps.get

      - name: Run tests
        run: mix test


