name: Publish VS Code extension

on: 
  push:
    tags:
      - '**'

jobs:
  publish:
    name: Publish 
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # - name: Setup elixir
      #   uses: erlef/setup-elixir@v1
      #   with:
      #     elixir-version: 1.13.4
      #     otp-version: 24.3.4

      # - name: Install elixir deps
      #   run: mix deps.get

      - name: Move necessary files
        run: |
          mkdir extensions/vscode/refactorex
          cp -r lib bin mix.exs mix.lock extensions/vscode/refactorex
          cp README.md LICENSE.md extensions/vscode

      - name: Install node deps
        run: npm install --prefix extensions/vscode

      - name: Update package.json version
        uses: maxgfr/github-change-json@main
        with:
          key: 'version'
          value: '${{ github.ref_name }}'
          path: extensions/vscode/package.json

      - name: Publish to Visual Studio Marketplace
        uses: HaaLeo/publish-vscode-extension@v1
        with:
          packagePath: extensions/vscode
          pat: ${{ secrets.VS_MARKETPLACE_TOKEN }}
          registryUrl: https://marketplace.visualstudio.com