name: Publish VS Code extension

on: 
  push:
    tags:
      - '**'

jobs:
  publish:
    name: Publish 
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Move necessary files
        run: mkdir extensions/vscode/refactorex
        run: cp -r lib bin deps mix.exs mix.lock extensions/vscode/refactorex
        run: cp README.md LICENSE.md extensions/vscode

      - name: Go to extension folder
        run: cd extensions/vscode

      - name: Install node deps
        run: npm install

      - name: Update package.json version
        uses: maxgfr/github-change-json@main
        with:
          key: 'version'
          value: '${{ github.ref_name }}'
          path: package.json
          commit: true 
          